#!/bin/bash
#author: Leo / b4nned
#date: 17/02/17 {dd/mm/yy}
#version 1.0
#See the file 'LICENSE', or visit www.gnu.org/licenses/gpl.txt

Change_Color () {
	color="\e[0m"
	divide=$[( $2 / 4 )]
	nice1_div=$[( $divide * 2 - 5 )]
	nice2_div=$[( $divide * 2 + 5 )]

	cold1_div=$[( $divide * 2 - 4 )]
	cold2_div=$[( $divide )]

	hot1_div=$[( $divide * 2 + 4 )]
	hot2_div=$[( $divide * 3 )]
	hot3_div=$[( $divide * 4 - 5 )]

	#echo $1 $2 $nice1_div $nice2_div $cold1_div $cold2_div $hot2_div $hot1_div

	if [[ "$1" > $nice1_div && "$1" < $nice2_div ]]; then
		color="\e[92;1m"

	elif [[ "$1" < $cold1_div ]]; then
		if [[ "$1" < $cold2_div ]]; then
			color="\e[89;104;1m"
		else
			color="\e[36;1m"
		fi

	elif [[ "$1" > $hot1_div ]]; then
		if [[ "$1" > $hot2_div ]]; then
			if [[ "$1" > $hot3_div ]]; then
				color="\e[89;101;1m"
			else
				color="\e[91;1m"
			fi
		else
			color="\e[93;1m"
		fi
	fi
}

echo -e "\n\n\n"

Show_info () {
	#a=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq)
	#b=$(bc -l <<< "$a / 1000")
	#echo ${b%00000000000000000}
	Reset
	vet_core=()
	vet_temp=()
	vet_htemp=()
	vet_etemp=()

	cores=$(sensors | grep Core | cut -b 6)
	temps=$(sensors | grep Core | cut -b 18-19)
	htemps=$(sensors | grep Core | cut -b 35-36)
	etemps=$(sensors | grep Core | cut -b 53-55)

	for i in $cores; do 
		vet_core+=($i);
	done

	for i in $temps; do 
		vet_temp+=($i); 
	done

	for i in $htemps; do 
		vet_htemp+=($i); 
	done

	for i in $etemps; do 
		vet_etemp+=($i); 
	done

	vetorlen=${#vet_core[*]}
	vetorlen=$[($vetorlen-1)]
	for i in $( seq 0 $vetorlen); do
		Change_Color ${vet_temp[$i]} ${vet_htemp[$i]} 
		#Change_Color 25 ${vet_htemp[$i]} 
		echo -e "\e[0m""\e[1mCore \e[94m$i\e[0;1m:   $color${vet_temp[$i]}°C"
	done
}

Reset () {
	echo -e "\e[0m\033[5A"
}

Start_mode () {
	if [ $1 == "0" ]; then
		k="0"
		while true; do
			Show_info
			sleep 1
			k=$[$k+1]
		done
	fi
}

p_list=()

if [ $# == "0" ]; then
	Start_mode 0
else
	for i in $(seq 1 $#); do
		p_list+=($i)
	done
fi



